### ISSUE TITLE
Make sure announcements update immediately.

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#10]

**Comment by conrad-vanl** [comment]
Fixed in https://github.com/watermarkchurch/clc-app-v2/commit/6c3a851934c9b5babf58d3e65530bf5d70d271c1

It's now a 2 minute cache, not immediate.

**Comment by frizman21** [comment]
@gburgett , please confirm that a CMS published announcement appears in two minutes on your phone.

**Comment by gburgett** [comment]
Confirmed - announcement update appears within 1 minute on the home page (This is fixed in the latest version which will be submitted to review today)
