### ISSUE TITLE
Switch to money-saving mode

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/clc-app-v2#106]
Currently running max-performance addons:
![image.png](https://zube.io/files/watermarkchurch/c12c37db2c7d0fb62af2e6216b3bf6a2-image.png)

Dial it down to free-tier

**Comment by rileyjhardy** [comment]
[CLC_Registrations_2022.csv](https://zube.io/files/watermarkchurch/aa8aae28b74aa1585bb09f2a850e571c-clc_registrations_2022.csv)

**Comment by gburgett** [comment]
@rileyjhardy last thought - would you document the steps you took to accomplish this so we can have them available for next year?
