### ISSUE TITLE
demonstration of how to flush the cache

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#11]
its on heroku

**Comment by gburgett** [comment]
![image](https://user-images.githubusercontent.com/430257/115563964-a9e68280-a27d-11eb-84ea-5b1cafc6fad8.png)
![image](https://user-images.githubusercontent.com/430257/115564055-bbc82580-a27d-11eb-966a-e43773eafa40.png)

![image](https://user-images.githubusercontent.com/430257/115563831-8b808700-a27d-11eb-8e85-e8dd49b70218.png)
![image](https://user-images.githubusercontent.com/430257/115563914-9f2bed80-a27d-11eb-8dc7-1ecd0cbcc2d9.png)
