### ISSUE TITLE
Allow Announcements to use a Video

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/clc-app-v2#111]
We want to be able to put a video on the Home (Announcement) page.

- [x] Add "Video" as an option to the Announcement content type
- [x] If video is present, play the video in the app when the announcement is clicked
- [x] Add a "play" icon overlay to the Announcement image

**Use standard react-native video player**

Figma
https://www.figma.com/file/D6Warg8Be5jhexIqwXYODf/CLC-app-(2022)?node-id=706%3A42&t=U9XMvrpm5wUMSJdg-0

![clc-announcement-video.png](https://zube.io/files/watermarkchurch/3e35da2fa24912723d9c5f8b9f983419-clc-announcement-video.png)

**Comment by jpowell** [comment]
@skipperpickle to provide guidance on play icon placement in announcement

**Comment by skipperpickle** [comment]
Added a view for the announcement card. Let me know if more is needed.
