### ISSUE TITLE
Banner images in announcements

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#116]
#### User Story
As an app user, I want only the most important announcements, and I want to know how important those are relative to the others in the list.

#### Problem statement
Can we have a banner announcement? 
- [ ] Optional text caption (i.e., don't display the text area if no text is supplied)
- [ ] Modify so that max-width determines the scale of the image, rather than scaling to max-height (but how will this affect the existing images?)
- Maintain rounded corners on the image only announcement cards

#### Relevant Information / Research / Back story
CLC team wants a place to persist a merch advertisement. 

##### Screenshots
When we post this 690x180 image: 
![clc-app-banner.png](https://zube.io/files/watermarkchurch/f2f18fb377b729d1d3604d63b7ec5248-clc-app-banner.png)

...currently we get this
![IMG_5EA40F85271C-1.jpeg](https://zube.io/files/watermarkchurch/be823f80ec37ac76feb8e675c276c920-img_5ea40f85271c-1.jpeg)

##### FIGMA REFERENCE

**Comment by jpowell** [comment]
Idea - this could be a home tab CTA that's separate from the announcements... do you have an ideal design for this?

**Comment by rileyjhardy** [comment]
@skipperpickle @jpowell Should this link directly to an external page? Or should it take me to a normal announcement view with a link in the content body?
