### ISSUE TITLE
understand impacts of caching

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#14]

**Comment by gburgett** [comment]
We are now setting the `stale-while-revalidate` option of the `cache-control` header.  This allows Fastly to serve up stale content while it goes and fetches the latest version.  We are using this in combination with a Contentful webhook to invalidate old cache data.  We expect this approach to provide snappy content updates while keeping aggressive caching in place.

**Comment by gburgett** [comment]
Need to investigate client side cache

@conrad-vanl do you have answers to these questions?
1. Inside the app, does the `InMemoryCache` respect cache-control headers?
2. If not, what are the criteria for invalidating cached data in the app?
3. Does the app perform a refresh on wake up from sleep?  Two possible cases:
    - Switched to another app and switched back
    - Had the app in the foreground and closed my phone, then at the end of a breakout I open my phone again & the app is still in the foreground

**Comment by conrad-vanl** [comment]
`InMemoryCache` **does** respect cache-control headers

Most of the queries in the app use a [`cache-and-network`](https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies) fetch policy which will display results from cache immediately, and then fetch updated content in the background. This will typically trigger whenever you open the app, although if you just had the app opened and quickly switched from one app and back, it may not re-trigger. It's based on the rendering of components and such.

The only thing I'm not super happy with is that the "My CLC" tab might have to be "Pull to refresh" to actually have your "Up Next" update. And the loading state isn't great. 

There's a way you could have fine-tuned control of this - by using the [AppState package](https://reactnative.dev/docs/appstate) and manually triggering a refetch when the app became active. If you wanted to try and implement this today and submit for review, I could walk you through it.
