### ISSUE TITLE
times on the My CLC are off (timezone?)

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#15]
Times are correct on the Schedule. They are off by 5 hours on the "My CLC" view.

![image](https://user-images.githubusercontent.com/11731079/115736749-25fdca80-a351-11eb-9eb2-593e44f644b6.png)

![image](https://user-images.githubusercontent.com/11731079/115736762-28f8bb00-a351-11eb-890a-5ff0bd80c2e5.png)

**Comment by gburgett** [comment]
Fixed by setting server TZ to US central - @frizman21 please verify

**Comment by frizman21** [comment]
@gburgett , Mandy was one who discovered the time issue. Please confirm with her.
