### ISSUE TITLE
Android: Viewing speakers shows "register" button

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/clc-app-v2#2]
Viewing a speaker on an event, the "register" button still showed up.  I clicked "register" but nothing showed up in the "my clc" view
![Screenshot_20210420-111310_CLC](https://user-images.githubusercontent.com/430257/115431371-d392a180-a1ca-11eb-9e1e-b673316573e4.jpg)

**Comment by conrad-vanl** [comment]
it's the same register button from the event you were looking at
