### ISSUE TITLE
Schedule - Truncated descriptions aren't continued on drilldown

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#20]
Via Luke Friesen
> In the Schedule tab, when clicking on workshops, I don’t see the description that is previewed (“a pre conference opportunity…”)  in that page, then expanded on the following page. i.e., can’t read the full description.

In Schedule tab: 
- [ ] Workshops
- [ ] Workshops (Cont.)
- [ ] Lunch

![image.png](https://zube.io/files/watermarkchurch/70b1228f4edd384ceebaed9184a58833-image.png)

![image.png](https://zube.io/files/watermarkchurch/0ebe3e686fe437cae67c2bb8495b9643-image.png)

**Comment by skipperpickle** [comment]
Zig is fixing this on the CMS side.

**Comment by jpowell** [comment]
👏🏽 🙌🏽
