### ISSUE TITLE
Farkle - Unclear how to keep dice

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#21]
Via Luke Friesen, Lance Sisco: 
> May be helpful to add some instructions that you have to click on the dice you want to keep. That wasn’t intuitive to me and I had to experiment. 

- [ ] When I roll the dice, display a hint “Select the dice you want to keep.” You can center this below the dice.
- [ ] Show the Keep button from the outset, but in a disabled state (grayed out) when no dice are selected. This will signal to me that something is required of me in order to be able to do that action.

**Comment by jpowell** [comment]
@skipperpickle my own personal feedback

> I also want to change the button function to be “Keep and roll again”, and “Keep and end turn”… something to that affect.
