### ISSUE TITLE
Tracks - Session listing - Overline text is too dark (dark mode)

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#24]
On iOS in dark mode, the overline text is too dark.

Light mode:
![image.png](https://zube.io/files/watermarkchurch/fe0a6941fd014c6dd6e52cef38494b74-image.png)

Dark mode:
![image.png](https://zube.io/files/watermarkchurch/d19d0b6ebfe0810ba8ae78ee0c53305c-image.png)

**Comment by gburgett** [comment]
@skipperpickle what color should it be?

**Comment by skipperpickle** [comment]
#b9a9b3 (light purple)
