### ISSUE TITLE
Landscape orientation - Back/Close controls disappear.

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#26]
iOS:
In a session description (and other screens with close and/or back buttons), close and back buttons disappear on swap to landscape orientation.

Switching back to portrait landscape, the buttons still remain inaccessible. You are stuck on the page. 

To restore the controls, you have to jump out of the app and back in.

Consider locking orientation of the app, if possible.

![IMG_5DB6A3FC0201-1.jpeg](https://zube.io/files/watermarkchurch/332e9683707d2c286908182346d3aae3-img_5db6a3fc0201-1.jpeg)

![IMG_42E84A1F8CAF-1.jpeg](https://zube.io/files/watermarkchurch/6adfc5edb296f9f7e155bd791e7f4b91-img_42e84a1f8caf-1.jpeg)

![IMG_4BA98AB69BA1-1.jpeg](https://zube.io/files/watermarkchurch/44e655d141d873197e2420c7e7a1fe18-img_4ba98ab69ba1-1.jpeg)

**Comment by gburgett** [comment]
Fixed by disableing landscape mode on the iOS app
