### ISSUE TITLE
Android: what does "Change Password" do?

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/clc-app-v2#3]
We're using phone number to log in correct?  Can we get rid of "Change password"?
![Screenshot_20210420-111759_CLC](https://user-images.githubusercontent.com/430257/115431469-f7ee7e00-a1ca-11eb-9d5c-85e9f0fc1176.jpg)

**Comment by conrad-vanl** [comment]
you can login with phone number or with an email address. We can't really detect which way you've chosen to login currently, so this password screen is needed
