### ISSUE TITLE
2021 Retro Notes

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#30]
Project Scope - good job up front. All the possible requirements. Need to be very clear next year what the requirement is, specifically around registration. 

Budget: $500 / month.

Editor / QA that reviews the website.

### Functionality
- [ ] Be able to send a push notification to all participants signed up for a specific event.
- [ ] Apparently App Store Honduras can’t download the app... not sure how that gets fixed at moment but a note for next time @jpowell 
- [ ] consulting calls baked in, with schedule caledndar lntegration
- [ ] Must support multiple conferences (last year) in the CMS. 
- [ ] Push notification inbox. 
- [ ] schedule tab didn't scroll to current time.
- [ ] breakout attendee list - would love to follow-up with those people.
- [ ] staff directory - with contact info. Events have speakers, and all their events. But not a way to find Wagnon and what he is speaking at.
- [ ] When viewing a track session list, display date + time of session on the list
- [ ] Session list within a Track should be time chronological order.

### Performance
- [ ] App struggled under the load during the breakout breaks. LOTS of people pounding the site.
- [ ] Capture production environment for full scale usage

**Comment by frizman21** [comment]
From @gburgett 
> In this case, if I had to do it for next year, I’d have a local redux state machine in the app that persists to phone storage.  Registrations would drive updates to redux and I’d look it up from there to drive the “my CLC” tab.  Content could still be a web request b/c as long as that’s not a personal query it can be cached at the CDN

**Comment by frizman21** [comment]
From @conrad-vanl :
> you know what I was also noodling on for next year....I bet that we can "preload" all of the conference info (all of the sessions, maps, locations, etc) with one graphql query and that way tapping around on the app doesn't generate a lot of queries that turn into loading state

**Comment by frizman21** [comment]
From @conrad-vanl:
> what sucks is I know the line of code causing these problems :confused: and I could fix it but it'd take a bit of work and not sure if it's worth trying to push something since we're more then halfway over now (edited)

**Comment by frizman21** [comment]
From @skipperpickle:

> I suspect that this might cause some misunderstanding:
Workshops have a notice that says “Workshops require advance registration during conference signups.
If I drill down to a workshop and select “Add to my schedule”, the feedback I get is “Registered”.
> 
> I think that feedback line should be “Added to My CLC” (since that is where it will show up) or “Added to Schedule”.
> 
> Note that on My CLC, the list of things that I’ve added to my schedule says “My Registered Events”.

**Comment by frizman21** [comment]
@conrad-vanl:
> i wasn't able ot test locally.....getting errors on -api boot i thin krelated to not having memcached stuff or something along those lines.....they were envinronment errors not code errors

**Comment by gburgett** [comment]
Report from a volunteer:

> when you click on a notification, it disappears and you can't see what it said. The notifications don't go anywhere.

**Comment by jpowell** [comment]
When viewing a track session list, display date + time of session on the list

**Comment by frizman21** [comment]
Robert Green to consider whether to allow participants to look each other up. Or connect by region.

**Comment by jpowell** [comment]
@mikezigster force rank for 2022:

 > @Justin Powell-
 >  
 > Here ya go. Let me know if you need anything else.
 >  
 > Strong Desire (Need to Haves)
 > Staff Consulting Calls
 > 1:1 Registration of specific events
 > Farkle App with Consequence Generator
 > UI Update - Track List display date + time of sessions
 > Session list within a Track should be time chronological order.
 > Schedule Tab - Scroll to current time (gray out past events)
 > Notification Inbox
 > _______
 > Desires (Like to Haves)
 > Live Chat
 > Push Notifications to specific audiences/events
 > Realtime Polling (Attendee Engagement)
 > Concrete examples and scope expectations needed from McGee
 > Current idea/approach-  https://www.mentimeter.com/ via embedded browser & QR codes
 > Staff Directory - Individual Staff pages already exist in each event type.
 > Post Resources
 >  
 > Dev Team Input Needed
 > App Store Honduras Issue
 > App struggled under the load during the breakout breaks. LOTS of people pounding the site.
 > Capture production environment for full scale usage
 >  
 > Kill
 > Must support multiple conferences (last year) in the CMS.
