### ISSUE TITLE
Track List - UI Updates

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/clc-app-v2#37]
- [x] add session datetime info
- [x] sort sessions in chronological order

![IMG_97FFE4DD2ACA-1.jpeg](https://zube.io/files/watermarkchurch/be922d5eee6ff6f83373ec3770439042-img_97ffe4dd2aca-1.jpeg)

**Comment by gburgett** [comment]
@skipperpickle I thought it best to re-use the way the Schedule tab does it and break it out by date. 
Thoughts?

![image.png](https://zube.io/files/watermarkchurch/2ce3444868b15f0c81db38084d924d01-image.png)

**Comment by skipperpickle** [comment]
> I thought it best to re-use the way the Schedule tab does it and break it out by date.
Thoughts?

Nice. I like it.
