### ISSUE TITLE
Farkle Consequence Generator

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/clc-app-v2#47]
User Stories: 
- As a CLC participant, I can view the list of Farkle consequences and select one.
- As a CLC participant, I can have a Farkle consequence selected randomly for me in the CLC app.

**IF ANIMATION IS COSTING TOO MUCH TIME - PLEASE COMMUNICATE!**

**Requirements**:
- My selected consequence should persist across sessions. 
- Current list has 59 consequences, with these parts: 
    - Farkle Consequence (name) - max chars: 30
    - Description - max chars: 400
- Let's prioritize simple animation over complex physics calculations

**IF ANIMATION IS COSTING TOO MUCH TIME - PLEASE COMMUNICATE!**

Nice to have:
- If a current consequence has been accepted / chosen, the view now presents the name and description of the consequence with a Done button
- floating button at bottom opening screen when current consequence is locked to shortcut to consequence screen

This spreadsheet has the most recent version of the consequence list:
[CLC.Farkle.Consequences.2022-03-04.xlsx FINAL DRAFT](https://zube.io/files/watermarkchurch/a49a87f16e96238ecc0de3098c91ee25-clc-farkle-consequences-2022-03-04.xlsx)

Wireframe: 
The picker component is based on the [iOS Picker control](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/). The idea here is to allow the player to review a consequence at will by "spinning" the picker manually. As each consequence receives focus, its name/description appears below the picker component. 

I can also select Spin the Wheel to see the picker rotate to a randomly selected consequence. 

Regardless of the consequence selection method, I can select Accept to "lock" the consequence in: the name and description become more prominent, the Done button appears, and the Picker no longer responds to input. When I select Done, this view returns to the ready state. 

We don't have to do it exactly this way, but I think the behavior and states are right. 
![image.png](https://zube.io/files/watermarkchurch/add6433c579c72b917cd891809460277-image.png)

Figma Reference (for wireframe):
https://www.figma.com/file/D6Warg8Be5jhexIqwXYODf/CLC-app-(2022)?node-id=3%3A38

**Comment by gburgett** [comment]
Train a neural net on a corpus of old farkle consequences and prompt it for new ones

**Comment by mikezigster** [comment]
@jpowell Working the details through with the culture team. When you do need firm direction?

**Comment by jpowell** [comment]
@mikezigster direction is for @skipperpickle to provide a design for this before end of this sprint (March 2). Then Gordon will begin these app tweaks + enhancements.

**Comment by mikezigster** [comment]
@skipperpickle I talked with Culture Team. They requested the following for the Farkle feature within the app:
- Randomized Result Button
- Button to send to a full list of consequences. We will have to figure out how this list will be presented (ig webpage, pdf, etc.)

[CLC Farkle Consequences 2022.xlsx](https://github.com/watermarkchurch/clc-app-v2/files/8119623/CLC.Farkle.Consequences.2022.xlsx)

**Comment by skipperpickle** [comment]
Here's a simple spinning wheel animation in CSS. 
http://jsfiddle.net/YNBxz/2/

**Comment by skipperpickle** [comment]
@jpowell Please review. I think I've done what I can here for now.

**Comment by skipperpickle** [comment]
Final edited draft of Consequence list is now attached in description.

**Comment by jpowell** [comment]
Instrument Claim and Done events tracking consequence as TItle
