### ISSUE TITLE
Android: clicking "Register" didn't add to my CLC

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/clc-app-v2#5]
I clicked "Register" here:
![image](https://user-images.githubusercontent.com/430257/115433157-d7272800-a1cc-11eb-988d-e3b96ee9ed10.png)
It didn't show up here:
![image](https://user-images.githubusercontent.com/430257/115433176-dd1d0900-a1cc-11eb-9b59-fe0e3e2bc2c9.png)

**Comment by conrad-vanl** [comment]
Did you try pulling-to-refresh on the My CLC screen? when you open that item back up, does it show as "Registered"?

**Comment by gburgett** [comment]
Yes, did a pull to refresh.  Item shows up as "registered".

Is there a spot to look at log entries related to someone's registration?  Would those be keyed by phone number / email?

**Comment by gburgett** [comment]
> Yes, did a pull to refresh. Item shows up as "registered".

To clarify - I did a pull to refresh and it's still not in "My CLC', but when I go back to the item it shows as "Registered".

I also tried closing and reopening the app

**Comment by gburgett** [comment]
It just updated! But then I went to change my schedule some more and it didn't update. Is there maybe a Cdn cache in front of that query?

**Comment by gburgett** [comment]
Fixed: caching issue
