### ISSUE TITLE
Can we delete the events association on a speaker?

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/clc-app-v2#52]
Speakers have many events AND Events also have many speakers... it appears that when rendering an event we are:
- rendering the speakers for that event populated from the event content type relationship
- rendering a speaker we're using the events that list a speaker NOT the events relationship on a Speaker

This seems unnecessarily confusing

**Comment by skipperpickle** [comment]
IIRC we still need this because we might want list events under a speaker, but not speakers under an event (e.g., John McGee's page might show that he's leading the Main Session, but on the Main Session page, we don't want John McGee to show up there).

**Comment by jpowell** [comment]
Yes - this was answered. Thanks for follow-up.
