### ISSUE TITLE
Staff Directory - index

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#54]
See watermarkchurch/clc-app-v2#43 for full constraints. 

Note that the designs provided are just a wireframe. We aren't changing text styles, colors, etc from those currently used in the app. 

**Requirements for Staff List (index)** (this is a new view): 
- [x] In the Connect index, I can select an item "Watermark Staff" to open the staff list. This should be hardcoded at the top of the resources section. (see screenshot)
- [x] In the staff list (header: "Watermark Staff"), I can see a list of ALL staff members as thumbnail portrait, name, title. "Name" is displayed as firstname lastname.
- [x] **ONLY** those selected to be displayed on conference directory should show up (option lives on Speaker object)
- [x] List is sorted alphabetically by lastname, firstname. 
- [ ] watermarkchurch/clc-app-v2#73

**Nice to have**
- [x] I can filter the staff list by name search field.

FIGMA REFERENCE
https://www.figma.com/file/D6Warg8Be5jhexIqwXYODf/CLC-app-(2022)?node-id=28%3A30

Wireframe of Watermark Staff List
![image.png](https://zube.io/files/watermarkchurch/f105ada68060fc05095c0a181ca01ee3-image.png) 

Watermark Staff list is available on the Connect tab:
![IMG_4580](https://user-images.githubusercontent.com/35932/156419877-be3aa8d6-d00e-4711-8530-5a1ddbb82dfe.jpeg)

**Comment by gburgett** [comment]
@jpowell would you grant me figma access?

**Comment by gburgett** [comment]
@skipperpickle what is the subtitle text color here?
![image.png](https://zube.io/files/watermarkchurch/09cf9a4abbbc00b84331fc49c2a9eb2c-image.png)

**Comment by skipperpickle** [comment]
@gburgett I'm using #6A6A6A for that. (But remember, I'm just trying to approximate colors I see already in the app, which I'm unable to sample reliably.)
