### ISSUE TITLE
Build pipeline failing

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/clc-app-v2#58]
https://github.com/watermarkchurch/clc-app-v2/actions/runs/1960123599

![image](https://user-images.githubusercontent.com/35932/159326225-781bbcb4-c098-472c-a61d-3afa029d52b8.png)

**Comment by jpowell** [comment]
Progress Update: I upgraded fastlane to the latest, re-ran cert / import / match commands and it appears that progress is being made for iOS...

**Comment by jpowell** [comment]
iOS builds are hanging on pushing to TestFlight

![image](https://user-images.githubusercontent.com/35932/159373572-f7c58b5d-0f18-4d4a-ac2e-dc1d5bd8f3db.png)

**Comment by jpowell** [comment]
Going to set `skip_waiting_for_build_processing` so that the github action can complete and not get hung on app store processing

**Comment by redreceipt** [comment]
It will eventually complete. It’s useful so you know it actually went through. But you can skip if you want.
