### ISSUE TITLE
Android: Hitting "back" too quickly causes crash

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/clc-app-v2#6]
If I click on a session and then click "Back" too quickly, I get into this state:
![image](https://user-images.githubusercontent.com/430257/115442063-34c07200-a1d7-11eb-9c4c-c24354577d00.png)

If I click on another session, the app crashes.

I can consistently reproduce this.

**Comment by gburgett** [comment]
@conrad-vanl any thoughts on this?  If it's a quick fix might as well get it in

**Comment by conrad-vanl** [comment]
No, I haven't seen this. I imagine it is only reproducible on Android?
