### ISSUE TITLE
Migrate Person data to Speakers

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/clc-app-v2#64]
We need to pull Person data from paper-signs contentful into Speaker content type for CLC app. Please follow below guidance for migration.

---

High-level task breakdown
- update speaker content type to support updates
- import person data from paper-signs into Speaker objects

Speaker Content type changes
- [ ] add email address (string)
- [ ] add team (string)
- [ ] default "on conference directory" boolean to yes
- [ ] if person image (asset) migration is easy then do it, otherwise forego

Speaker import guidance from paper signs Person:
- email maps to email
- `Person.title` should overwrite `Speaker.summary`
- team should be derived from the Team objects that include the Person and where team is "listed" `yes`
- If a Speaker exists with a matching name, update email, team
- If Speaker bio is empty... add the following content:

```
__{insert Person title}__
[Read ___'s Bio](staff bio link on wm.org)
```

**Comment by gburgett** [comment]
@jpowell there are multiple "Team" objects which reference Bruce Kendrick, but the Person record in paper-signs has this for his "team":
![image.png](https://zube.io/files/watermarkchurch/a90111d056ce76e66df98e3e2e5f4d02-image.png)

I feel that the "team" string field on the Person record is more accurate and think that we shouldn't look up based on the "Team" objects at all.

**Comment by jpowell** [comment]
> @jpowell there are multiple "Team" objects which reference Bruce Kendrick, but the Person record in paper-signs has this for his "team":
> 
> ![image.png](https://zube.io/files/watermarkchurch/a90111d056ce76e66df98e3e2e5f4d02-image.png)
> 
> 
> 
> I feel that the "team" string field on the Person record is more accurate and think that we shouldn't look up based on the "Team" objects at all.
> 
> 
> 
> Edit: I guess bruce only has one team that is "listed".  I'll use that.

I would agree, except that we found those team strings to not be accurate. Bruce Kendrick might be an outlier here, among a few others in leadership whose team has shifted.

We can talk Monday
