### ISSUE TITLE
Remove "Registration not Required" label

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#7]
On Workshops, we want to remove this label. People can add to calendar. BUT pre-registration is required. Which makes the "registration not required" confusing.

![Image from iOS (6)](https://user-images.githubusercontent.com/11731079/115447956-b49e0a80-a1de-11eb-9481-5f1c1be5c0f1.png)

Furthermore, on all other no-cap events (like breakouts), the label is less helpful.

**Comment by conrad-vanl** [comment]
https://github.com/watermarkchurch/clc-app-v2/commit/9ff0c01373244d2fabee51e29e861a9b0378c849
