### ISSUE TITLE
Dice Role Website

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#8]
We need to create a COVID friendly dice roll in the app. 

The plan is to use a in-app browser for this feature.

We need to put the follow code snippet somewhere on the web.
https://codesandbox.io/s/08unw

Send conrad the URL for it, so that he can load that link into the app.

**Comment by jpowell** [comment]
oh man

**Comment by gburgett** [comment]
https://watermarkchurch.github.io/clc-app-v2/roll.html

**Comment by frizman21** [comment]
> oh man

??

**Comment by mikezigster** [comment]
@gburgett Can we customize the color on this one? CLC orange background with the purple button.
