### ISSUE TITLE
make sure devops is ready for next week

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-app-v2#9]
Get specs from @conrad-vanl 

Chat with @watermarkgeek 

@gburgett to stress testing against login end-points.

**Comment by conrad-vanl** [comment]
Okay so here are the queries and mutations we use for user login. We use graphql and our graphql server accepts both GET and POST requests on Queries, but you must use POST on Mutations. If you need info on how to make GraphQL requests over something like Curl, I can dig up docs, but it's pretty standard. You can test out these endpoints by hand by opening GraphiQL - https://wcc-clc-v2.herokuapp.com

First, when a user goes to login, this query is ran to check if the user is new or existing:

```gql
query checkUserExists {
  userExists(identity: "9723654600")
}
```

Then, to send the SMS Pin code over text:

```gql
mutation requestSMSLoginPin {
	requestSmsLoginPin(phoneNumber:"9723654600") {
    success
  }
}
```

Once a user receives their pin, we use this to log them in:

```gql
mutation loginWithSMSPin {
  authenticateWithSms(phoneNumber:"9723654600", pin: "1234") {
    token
    user {
      id
    }
  }
}
```

Login in with Email/Password uses this mutation:

```gql
mutation loginWithEmailPassword {
  authenticate(identity: "email", password: "password") {
		token
    user {
      id
    }
  }
}
```

And lastly, to sign a new user up, we use these endpoint:

```gql
mutation {
  registerPerson(email:"email", password:"passowrd", userProfile: [{field:FirstName,value:"firstname"},{field:LastName,value:"lastname"}]) {
    user {
      id
    }
    token
  }
}
```

```gql
mutation {
  registerWithSms(phoneNumber:"phoneNumber", password:"passowrd", userProfile: [{field:FirstName,value:"firstname"},{field:LastName,value:"lastname"}]) {
    user {
      id
    }
    token
  }
}
```

If you are testing some of our queries, they may require an authToken to execute. You can get a `token` in the above mutations (you can see `token` in the request) and you said an `Authorization` header with the value of the token:

<img width="600" alt="Screen Shot 2021-04-21 at 9 00 20 AM" src="https://user-images.githubusercontent.com/103927/115566605-0185ed80-a280-11eb-818f-1928e5f29aad.png">


Here is our document on load testing Apollos Apps: https://apollosapp.io/docs/load-testing

**Comment by conrad-vanl** [comment]
Also, if you use the Heroku URL for load testing, that will bypass the CDN
