### ISSUE TITLE
Farkle Consequence UI colors

### ISSUE THREAD

**Issue by skipperpickle** [watermarkchurch/clc-app-v2#92]
- [x] Change the label on the Done button to "Consequence Complete!"
- [ ] Colors: 
    - CLC Orange: #EF5E24
    - Plum: #542A44
    - Old Lilac: #8D7484

For the disabled version of the Spin The Wheel button, I'm setting the Orange color to 70% opacity, but if the app already has a generic disabled state, that might work just as well. 

Figma Reference: 
https://www.figma.com/file/D6Warg8Be5jhexIqwXYODf/CLC-app-(2022)?node-id=12%3A32

![image.png](https://zube.io/files/watermarkchurch/7a9a346c7c3d71dc68d54ce9755328fc-image.png)

![image.png](https://zube.io/files/watermarkchurch/abdc3f70c7e4c79acfdd09125ddf860e-image.png)

![image](https://user-images.githubusercontent.com/38433347/163479879-7abf3420-b862-42b0-b75c-4001fa52ed9f.png)

**Comment by skipperpickle** [comment]
@gburgett Colors for the Farkle consequences wheel.

**Comment by gburgett** [comment]
@skipperpickle do you have a dark mode theme for this?

**Comment by skipperpickle** [comment]
> do you have a dark mode theme for this?

@gburgett I added a dark version screen in Figma. 

The colored sections don't change between dark/light mode, so I suspect the real answer is "no, I don't."
